baseURL: http://muhrifqii.com/
languageCode: en-us
title: "muhrifqii"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
#googleAnalytics: UA-XXXXXXXXX-X
disqusShortname: muhrifqii
enableEmoji: true
params:
  copyright: © 2020 Muhammad Rifqi Fatchurrahman
  description: Portfolio and blog of Muhammad Rifqi Fatchurrahman
  background: "img/background.jpg"

  logo:
    main: img/logo_t.png
    inverted: img/logo_t.png
    favicon: img/logo_t.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/muhrifqii
  enableBlogPost: true
  enableTOC: true
#  customMenus:
#    - name: Notes
#      url: https://hossainnotes.netlify.app/docs/example/
#  newsletter:
#    enable: true
  author:
    name: "Muhammad Rifqi Fatchurrahman"
    nickname: "Rifqi"
    image: "img/wa.jpg"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "muh_rif@live.com"
#      phone: "+0123456789"
    summary:
      - Software Engineer
      - Working on native mobile both iOS and android
#      - Kotlin, Swift, Java are my primary language
#      - Also work on back-end with Spring or Go
